services:
  - type: web
    name: nllb-translator
    runtime: docker
    repo: https://github.com/Infoser/nllb-translator
    plan: standard
    healthCheckPath: /load-status
    envVars:
      - key: HF_MODEL_REPO
        value: infoser090/AksharaDhara
      - key: HF_HOME
        value: /tmp/hf_cache
      - key: SECRET_KEY
        generateValue: true
